# Importing libraries

In [3]:
import pandas as pd
import numpy as np
import os

In [5]:
# Assigning path
path = r'C:\Users\Shruthi\Desktop\CF_Tasks\21-06-2023_Instacart_Basket_Analysis'

In [6]:
ords_prods_merge = pd.read_pickle(os.path.join(path, '2. Data', 'Prepared data', 'orders_products_merged_new.pkl'))

In [7]:
# Creating subset
df = ords_prods_merge[:1000000]

In [8]:
df.shape

(1000000, 21)

In [9]:
df.head()

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,...,product_name,aisle_id,department_id,prices,_merge,price_range_loc,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,Soda,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,Soda,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Average orders
2,473747,1,prior,3,3,12,21.0,196,1,1,...,Soda,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,Soda,77,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Average orders
4,431534,1,prior,5,4,15,28.0,196,1,1,...,Soda,77,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders

In [10]:
# Grouping data
df.groupby('product_name')

In [11]:
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

In [12]:
# Aggregation using mean() function
df.groupby('department_id')['order_number'].mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

In [13]:
# Performing multiple aggregations
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
4                18.825780   1  99
7                17.472355   1  99
13               17.993423   1  99
14               19.246334   1  99
16               19.463012   1  99
17               11.294069   1  98
19               19.305237   1  99
20               17.599636   1  99

In [14]:
# Creating max_order column
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [15]:
# Checking
ords_prods_merge.head()

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,...,aisle_id,department_id,prices,_merge,price_range_loc,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,10
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,10
2,473747,1,prior,3,3,12,21.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,10
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Average orders,10
4,431534,1,prior,5,4,15,28.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,10

In [16]:
pd.options.display.max_rows = None

In [18]:
# Checking
ords_prods_merge.head(100)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,...,aisle_id,department_id,prices,_merge,price_range_loc,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,10
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,10
2,473747,1,prior,3,3,12,21.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,10
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Average orders,10
4,431534,1,prior,5,4,15,28.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,10
5,3367565,1,prior,6,2,7,19.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,10
6,550135,1,prior,7,1,9,20.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,10
7,3108588,1,prior,8,1,14,14.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,10
8,2295261,1,prior,9,1,16,0.0,196,4,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,10
9,2550362,1,prior,10,4,8,30.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Average orders,10
10,2968173,15,prior,15,1,9,7.0,196,2,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,22
11,1870022,15,prior,17,2,16,8.0,196,6,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,22
12,1911383,15,prior,18,2,11,7.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,22
13,2715276,15,prior,21,1,9,7.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,22
14,487368,15,prior,22,1,10,14.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,22
15,2293453,19,prior,2,5,14,6.0,196,3,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,9
16,1973799,19,prior,5,6,12,8.0,196,15,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,9
17,532817,19,prior,7,4,17,6.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Average orders,9
18,1573906,21,prior,10,3,10,6.0,196,2,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,33
19,1593000,31,prior,10,3,8,7.0,196,17,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,20
20,2231262,31,prior,17,3,11,8.0,196,14,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,20
21,2580647,43,prior,6,4,16,4.0,196,9,0,...,77,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,11
22,2187180,43,prior,9,4,12,3.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,11
23,2497897,52,prior,1,1,9,NaN,196,4,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27
24,1318871,52,prior,2,1,10,7.0,196,5,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27
25,1261384,52,prior,3,1,10,7.0,196,3,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27
26,580568,52,prior,5,2,10,8.0,196,6,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27
27,2428073,52,prior,7,2,7,8.0,196,5,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,27
28,342306,52,prior,9,1,11,7.0,196,5,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27
29,1520353,52,prior,10,2,10,8.0,196,4,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27
30,2542086,52,prior,11,2,9,7.0,196,3,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27
31,944694,52,prior,12,1,16,6.0,196,7,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27
32,1268191,52,prior,15,2,11,8.0,196,3,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27
33,1122089,52,prior,17,2,10,6.0,196,4,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27
34,1498922,52,prior,18,2,10,14.0,196,6,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27
35,180919,52,prior,19,3,8,8.0,196,4,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,27
36,2695875,52,prior,21,5,10,30.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27
37,3205960,67,prior,1,3,11,NaN,196,1,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,24
38,970922,67,prior,2,1,15,5.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24
39,596585,67,prior,3,1,13,7.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24
40,2037087,67,prior,4,2,9,8.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24
41,2474111,67,prior,5,3,14,8.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,24
42,1568481,67,prior,6,3,12,7.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,24
43,2048527,67,prior,8,2,11,7.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24
44,2389031,67,prior,9,2,14,7.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24
45,2378562,67,prior,10,1,10,6.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24
46,1515698,67,prior,11,1,11,7.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24
47,1928050,67,prior,12,2,12,8.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24
48,1949274,67,prior,13,1,10,6.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24
49,551869,67,prior,14,1,9,7.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24
50,768572,67,prior,16,4,10,9.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,24
51,150528,67,prior,18,5,16,4.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24
52,29758,67,prior,19,0,14,9.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Busiest day,Busiest days,Most orders,24
53,1558976,67,prior,21,1,9,5.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24
54,863974,67,prior,22,1,11,14.0,196,3,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24
55,2308399,67,prior,23,1,14,14.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24
56,2759128,81,prior,3,1,9,14.0,196,2,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,7
57,1812985,81,prior,5,2,20,30.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,7
58,1889835,82,prior,1,3,15,NaN,196,6,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,19
59,499460,82,prior,3,5,10,5.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,19
60,2728456,82,prior,4,0,11,16.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Busiest day,Busiest days,Most orders,19
61,2653743,82,prior,6,4,9,13.0,196,5,1,...,77,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,19
62,1358880,82,prior,9,1,10,30.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,19
63,343588,82,prior,10,2,11,1.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,19
64,3034663,82,prior,15,2,11,12.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,19
65,147262,82,prior,18,1,13,7.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,19
66,3144004,82,prior,19,2,15,8.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,19
67,2126069,98,prior,3,0,9,25.0,196,7,0,...,77,7,9.0,both,NaN,Mid-range product,Busiest day,Busiest days,Most orders,14
68,2210120,98,prior,7,5,14,5.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,14
69,681011,98,prior,9,3,9,30.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,14
70,2846344,98,prior,11,4,13,15.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,14
71,747431,98,prior,12,6,13,30.0,196,4,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,14
72,2383054,98,prior,13,4,11,30.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,14
73,1993729,98,prior,14,5,8,8.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,14
74,1403849,109,prior,3,3,17,9.0,196,5,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,6
75,520620,120,prior,1,3,11,NaN,196,2,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,3
76,3273029,120,prior,3,2,8,19.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,3
77,1861943,185,prior,2,1,12,25.0,196,10,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,6
78,2040988,195,prior,1,1,14,NaN,196,2,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,58
79,1680569,195,prior,8,1,9,4.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,58
80,276171,195,prior,19,5,11,3.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,58
81,2744976,195,prior,22,5,10,7.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,58
82,2781919,195,prior,25,1,14,4.0,196,1,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,58
83,1738718,195,prior,31,2,8,4.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,58
84,3058369,195,prior,34,3,10,6.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,58
85,1485596,195,prior,37,2,15,0.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,58
86,417035,195,prior,40,3,16,2.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,58
87,1615297,195,prior,47,5,10,2.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,58
88,1765587,195,prior,52,3,12,2.0,196,3,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,58
89,745908,195,prior,57,4,11,3.0,196,3,1,...,77,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,58
90,2505656,222,prior,17,2,12,1.0,196,2,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,70
91,3268370,222,prior,38,5,15,1.0,196,6,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,70
92,2016711,290,prior,9,5,19,6.0,196,8,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,51
93,2706088,290,prior,28,6,10,7.0,196,16,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,51
94,1952286,331,prior,6,5,16,30.0,196,8,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,8
95,3226575,360,prior,1,5,12,NaN,196,1,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,3
96,1469869,377,prior,3,5,17,3.0,196,9,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,3
97,1927023,387,prior,2,4,10,22.0,196,3,0,...,77,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,8
98,858092,420,prior,4,1,19,30.0,196,2,0,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Average orders,22
99,119314,420,prior,5,3,19,16.0,196,2,1,...,77,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,22

In [19]:
# Creating flag
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [20]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [21]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [22]:
ords_prods_merge['loyalty_flag'].value_counts(dropna= False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [23]:
# Checking
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             2
2         1      New customer             3
3         1      New customer             4
4         1      New customer             5
5         1      New customer             6
6         1      New customer             7
7         1      New customer             8
8         1      New customer             9
9         1      New customer            10
10       15  Regular customer            15
11       15  Regular customer            17
12       15  Regular customer            18
13       15  Regular customer            21
14       15  Regular customer            22
15       19      New customer             2
16       19      New customer             5
17       19      New customer             7
18       21  Regular customer            10
19       31  Regular customer            10
20       31  Regular customer            17
21       43  Regular customer             6
22       43  Regular customer             9
23       52  Regular customer             1
24       52  Regular customer             2
25       52  Regular customer             3
26       52  Regular customer             5
27       52  Regular customer             7
28       52  Regular customer             9
29       52  Regular customer            10
30       52  Regular customer            11
31       52  Regular customer            12
32       52  Regular customer            15
33       52  Regular customer            17
34       52  Regular customer            18
35       52  Regular customer            19
36       52  Regular customer            21
37       67  Regular customer             1
38       67  Regular customer             2
39       67  Regular customer             3
40       67  Regular customer             4
41       67  Regular customer             5
42       67  Regular customer             6
43       67  Regular customer             8
44       67  Regular customer             9
45       67  Regular customer            10
46       67  Regular customer            11
47       67  Regular customer            12
48       67  Regular customer            13
49       67  Regular customer            14
50       67  Regular customer            16
51       67  Regular customer            18
52       67  Regular customer            19
53       67  Regular customer            21
54       67  Regular customer            22
55       67  Regular customer            23
56       81      New customer             3
57       81      New customer             5
58       82  Regular customer             1
59       82  Regular customer             3

# Finding the mean orders

In [24]:
# Grouping by "product_name" 
ords_prods_merge.groupby('product_name')

In [25]:
# Split the data into groups by "department_id" and apply agg function
ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

-- There were differences in the mean orders when calculated using the entire dataframe rather than the subset: the minimum mean order in the subset is 11.3 while it is 15.2 in the dataframe, and the maximum mean in the subset is 19.5, 20.1 in the dataframe (not including department 21, the "missing" category).

# Creating loyalty flag

In [26]:
# Creating max_order column
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [27]:
pd.options.display.max_rows = None

In [28]:
# Checking
ords_prods_merge.head(100)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,...,department_id,prices,_merge,price_range_loc,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,10,New customer
2,473747,1,prior,3,3,12,21.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,10,New customer
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Average orders,10,New customer
4,431534,1,prior,5,4,15,28.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,10,New customer
5,3367565,1,prior,6,2,7,19.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer
6,550135,1,prior,7,1,9,20.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer
7,3108588,1,prior,8,1,14,14.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer
8,2295261,1,prior,9,1,16,0.0,196,4,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer
9,2550362,1,prior,10,4,8,30.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Average orders,10,New customer
10,2968173,15,prior,15,1,9,7.0,196,2,0,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
11,1870022,15,prior,17,2,16,8.0,196,6,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer
12,1911383,15,prior,18,2,11,7.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer
13,2715276,15,prior,21,1,9,7.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
14,487368,15,prior,22,1,10,14.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
15,2293453,19,prior,2,5,14,6.0,196,3,0,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer
16,1973799,19,prior,5,6,12,8.0,196,15,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer
17,532817,19,prior,7,4,17,6.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Average orders,9,New customer
18,1573906,21,prior,10,3,10,6.0,196,2,0,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,33,Regular customer
19,1593000,31,prior,10,3,8,7.0,196,17,0,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,20,Regular customer
20,2231262,31,prior,17,3,11,8.0,196,14,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,20,Regular customer
21,2580647,43,prior,6,4,16,4.0,196,9,0,...,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,11,Regular customer
22,2187180,43,prior,9,4,12,3.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,11,Regular customer
23,2497897,52,prior,1,1,9,NaN,196,4,0,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer
24,1318871,52,prior,2,1,10,7.0,196,5,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer
25,1261384,52,prior,3,1,10,7.0,196,3,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer
26,580568,52,prior,5,2,10,8.0,196,6,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer
27,2428073,52,prior,7,2,7,8.0,196,5,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,27,Regular customer
28,342306,52,prior,9,1,11,7.0,196,5,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer
29,1520353,52,prior,10,2,10,8.0,196,4,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer
30,2542086,52,prior,11,2,9,7.0,196,3,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer
31,944694,52,prior,12,1,16,6.0,196,7,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer
32,1268191,52,prior,15,2,11,8.0,196,3,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer
33,1122089,52,prior,17,2,10,6.0,196,4,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer
34,1498922,52,prior,18,2,10,14.0,196,6,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer
35,180919,52,prior,19,3,8,8.0,196,4,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,27,Regular customer
36,2695875,52,prior,21,5,10,30.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer
37,3205960,67,prior,1,3,11,NaN,196,1,0,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer
38,970922,67,prior,2,1,15,5.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer
39,596585,67,prior,3,1,13,7.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer
40,2037087,67,prior,4,2,9,8.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer
41,2474111,67,prior,5,3,14,8.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer
42,1568481,67,prior,6,3,12,7.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer
43,2048527,67,prior,8,2,11,7.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer
44,2389031,67,prior,9,2,14,7.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer
45,2378562,67,prior,10,1,10,6.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer
46,1515698,67,prior,11,1,11,7.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer
47,1928050,67,prior,12,2,12,8.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer
48,1949274,67,prior,13,1,10,6.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer
49,551869,67,prior,14,1,9,7.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer
50,768572,67,prior,16,4,10,9.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,24,Regular customer
51,150528,67,prior,18,5,16,4.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer
52,29758,67,prior,19,0,14,9.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Busiest day,Busiest days,Most orders,24,Regular customer
53,1558976,67,prior,21,1,9,5.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer
54,863974,67,prior,22,1,11,14.0,196,3,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer
55,2308399,67,prior,23,1,14,14.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer
56,2759128,81,prior,3,1,9,14.0,196,2,0,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,7,New customer
57,1812985,81,prior,5,2,20,30.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,7,New customer
58,1889835,82,prior,1,3,15,NaN,196,6,0,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,19,Regular customer
59,499460,82,prior,3,5,10,5.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer
60,2728456,82,prior,4,0,11,16.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Busiest day,Busiest days,Most orders,19,Regular customer
61,2653743,82,prior,6,4,9,13.0,196,5,1,...,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,19,Regular customer
62,1358880,82,prior,9,1,10,30.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,19,Regular customer
63,343588,82,prior,10,2,11,1.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer
64,3034663,82,prior,15,2,11,12.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer
65,147262,82,prior,18,1,13,7.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,19,Regular customer
66,3144004,82,prior,19,2,15,8.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer
67,2126069,98,prior,3,0,9,25.0,196,7,0,...,7,9.0,both,NaN,Mid-range product,Busiest day,Busiest days,Most orders,14,Regular customer
68,2210120,98,prior,7,5,14,5.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,14,Regular customer
69,681011,98,prior,9,3,9,30.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,14,Regular customer
70,2846344,98,prior,11,4,13,15.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,14,Regular customer
71,747431,98,prior,12,6,13,30.0,196,4,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,14,Regular customer
72,2383054,98,prior,13,4,11,30.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,14,Regular customer
73,1993729,98,prior,14,5,8,8.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,14,Regular customer
74,1403849,109,prior,3,3,17,9.0,196,5,0,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,6,New customer
75,520620,120,prior,1,3,11,NaN,196,2,0,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,3,New customer
76,3273029,120,prior,3,2,8,19.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,3,New customer
77,1861943,185,prior,2,1,12,25.0,196,10,0,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,6,New customer
78,2040988,195,prior,1,1,14,NaN,196,2,0,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer
79,1680569,195,prior,8,1,9,4.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer
80,276171,195,prior,19,5,11,3.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer
81,2744976,195,prior,22,5,10,7.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer
82,2781919,195,prior,25,1,14,4.0,196,1,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer
83,1738718,195,prior,31,2,8,4.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,58,Loyal customer
84,3058369,195,prior,34,3,10,6.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,58,Loyal customer
85,1485596,195,prior,37,2,15,0.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer
86,417035,195,prior,40,3,16,2.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,58,Loyal customer
87,1615297,195,prior,47,5,10,2.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer
88,1765587,195,prior,52,3,12,2.0,196,3,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,58,Loyal customer
89,745908,195,prior,57,4,11,3.0,196,3,1,...,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,58,Loyal customer
90,2505656,222,prior,17,2,12,1.0,196,2,0,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,70,Loyal customer
91,3268370,222,prior,38,5,15,1.0,196,6,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,70,Loyal customer
92,2016711,290,prior,9,5,19,6.0,196,8,0,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,51,Loyal customer
93,2706088,290,prior,28,6,10,7.0,196,16,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,51,Loyal customer
94,1952286,331,prior,6,5,16,30.0,196,8,0,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,8,New customer
95,3226575,360,prior,1,5,12,NaN,196,1,0,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,3,New customer
96,1469869,377,prior,3,5,17,3.0,196,9,0,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,3,New customer
97,1927023,387,prior,2,4,10,22.0,196,3,0,...,7,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,8,New customer
98,858092,420,prior,4,1,19,30.0,196,2,0,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Average orders,22,Regular customer
99,119314,420,prior,5,3,19,16.0,196,2,1,...,7,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,22,Regular customer

In [29]:
# Creating loyalty_flag
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [30]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [31]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [32]:
# Checking frequencies of loyalty flag
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

# Finding the mean of the product prices of loyal customers

In [33]:
# Grouping by "prices" 
ords_prods_merge.groupby('prices')

In [34]:
# Split the data into groups by "loyalty_flag" and calculate the mean for each "prices" column
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean']})

                     prices
                       mean
loyalty_flag
Loyal customer    10.386336
New customer      13.294670
Regular customer  12.495717

# Creating spending flag

In [35]:
# Creating column mean_price and grouping by user id and applying mean function on prices column
ords_prods_merge['mean_price'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [36]:
# Checking
ords_prods_merge.head(100)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,...,prices,_merge,price_range_loc,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,mean_price
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797
2,473747,1,prior,3,3,12,21.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
4,431534,1,prior,5,4,15,28.0,196,1,1,...,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797
5,3367565,1,prior,6,2,7,19.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797
6,550135,1,prior,7,1,9,20.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
7,3108588,1,prior,8,1,14,14.0,196,2,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
8,2295261,1,prior,9,1,16,0.0,196,4,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
9,2550362,1,prior,10,4,8,30.0,196,1,1,...,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
10,2968173,15,prior,15,1,9,7.0,196,2,0,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556
11,1870022,15,prior,17,2,16,8.0,196,6,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,3.980556
12,1911383,15,prior,18,2,11,7.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,3.980556
13,2715276,15,prior,21,1,9,7.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556
14,487368,15,prior,22,1,10,14.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556
15,2293453,19,prior,2,5,14,6.0,196,3,0,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,8.372059
16,1973799,19,prior,5,6,12,8.0,196,15,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,8.372059
17,532817,19,prior,7,4,17,6.0,196,1,1,...,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Average orders,9,New customer,8.372059
18,1573906,21,prior,10,3,10,6.0,196,2,0,...,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,33,Regular customer,7.012683
19,1593000,31,prior,10,3,8,7.0,196,17,0,...,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,20,Regular customer,8.137793
20,2231262,31,prior,17,3,11,8.0,196,14,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,20,Regular customer,8.137793
21,2580647,43,prior,6,4,16,4.0,196,9,0,...,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,11,Regular customer,7.444898
22,2187180,43,prior,9,4,12,3.0,196,1,1,...,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,11,Regular customer,7.444898
23,2497897,52,prior,1,1,9,NaN,196,4,0,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
24,1318871,52,prior,2,1,10,7.0,196,5,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
25,1261384,52,prior,3,1,10,7.0,196,3,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
26,580568,52,prior,5,2,10,8.0,196,6,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
27,2428073,52,prior,7,2,7,8.0,196,5,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,27,Regular customer,6.356287
28,342306,52,prior,9,1,11,7.0,196,5,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
29,1520353,52,prior,10,2,10,8.0,196,4,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
30,2542086,52,prior,11,2,9,7.0,196,3,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
31,944694,52,prior,12,1,16,6.0,196,7,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
32,1268191,52,prior,15,2,11,8.0,196,3,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
33,1122089,52,prior,17,2,10,6.0,196,4,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
34,1498922,52,prior,18,2,10,14.0,196,6,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
35,180919,52,prior,19,3,8,8.0,196,4,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,27,Regular customer,6.356287
36,2695875,52,prior,21,5,10,30.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
37,3205960,67,prior,1,3,11,NaN,196,1,0,...,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790
38,970922,67,prior,2,1,15,5.0,196,2,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
39,596585,67,prior,3,1,13,7.0,196,2,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
40,2037087,67,prior,4,2,9,8.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790
41,2474111,67,prior,5,3,14,8.0,196,2,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790
42,1568481,67,prior,6,3,12,7.0,196,2,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790
43,2048527,67,prior,8,2,11,7.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790
44,2389031,67,prior,9,2,14,7.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790
45,2378562,67,prior,10,1,10,6.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
46,1515698,67,prior,11,1,11,7.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
47,1928050,67,prior,12,2,12,8.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790
48,1949274,67,prior,13,1,10,6.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
49,551869,67,prior,14,1,9,7.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
50,768572,67,prior,16,4,10,9.0,196,1,1,...,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,24,Regular customer,7.656790
51,150528,67,prior,18,5,16,4.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790
52,29758,67,prior,19,0,14,9.0,196,2,1,...,9.0,both,NaN,Mid-range product,Busiest day,Busiest days,Most orders,24,Regular customer,7.656790
53,1558976,67,prior,21,1,9,5.0,196,2,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
54,863974,67,prior,22,1,11,14.0,196,3,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
55,2308399,67,prior,23,1,14,14.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
56,2759128,81,prior,3,1,9,14.0,196,2,0,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,7,New customer,8.165385
57,1812985,81,prior,5,2,20,30.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,7,New customer,8.165385
58,1889835,82,prior,1,3,15,NaN,196,6,0,...,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,19,Regular customer,6.441221
59,499460,82,prior,3,5,10,5.0,196,2,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer,6.441221
60,2728456,82,prior,4,0,11,16.0,196,1,1,...,9.0,both,NaN,Mid-range product,Busiest day,Busiest days,Most orders,19,Regular customer,6.441221
61,2653743,82,prior,6,4,9,13.0,196,5,1,...,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,19,Regular customer,6.441221
62,1358880,82,prior,9,1,10,30.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,19,Regular customer,6.441221
63,343588,82,prior,10,2,11,1.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer,6.441221
64,3034663,82,prior,15,2,11,12.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer,6.441221
65,147262,82,prior,18,1,13,7.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,19,Regular customer,6.441221
66,3144004,82,prior,19,2,15,8.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer,6.441221
67,2126069,98,prior,3,0,9,25.0,196,7,0,...,9.0,both,NaN,Mid-range product,Busiest day,Busiest days,Most orders,14,Regular customer,8.028000
68,2210120,98,prior,7,5,14,5.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,14,Regular customer,8.028000
69,681011,98,prior,9,3,9,30.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,14,Regular customer,8.028000
70,2846344,98,prior,11,4,13,15.0,196,2,1,...,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,14,Regular customer,8.028000
71,747431,98,prior,12,6,13,30.0,196,4,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,14,Regular customer,8.028000
72,2383054,98,prior,13,4,11,30.0,196,1,1,...,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,14,Regular customer,8.028000
73,1993729,98,prior,14,5,8,8.0,196,2,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,14,Regular customer,8.028000
74,1403849,109,prior,3,3,17,9.0,196,5,0,...,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,6,New customer,5.850725
75,520620,120,prior,1,3,11,NaN,196,2,0,...,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,3,New customer,9.385714
76,3273029,120,prior,3,2,8,19.0,196,2,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,3,New customer,9.385714
77,1861943,185,prior,2,1,12,25.0,196,10,0,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,6,New customer,7.715000
78,2040988,195,prior,1,1,14,NaN,196,2,0,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer,7.149730
79,1680569,195,prior,8,1,9,4.0,196,2,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer,7.149730
80,276171,195,prior,19,5,11,3.0,196,2,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer,7.149730
81,2744976,195,prior,22,5,10,7.0,196,2,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer,7.149730
82,2781919,195,prior,25,1,14,4.0,196,1,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer,7.149730
83,1738718,195,prior,31,2,8,4.0,196,2,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,58,Loyal customer,7.149730
84,3058369,195,prior,34,3,10,6.0,196,2,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,58,Loyal customer,7.149730
85,1485596,195,prior,37,2,15,0.0,196,2,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer,7.149730
86,417035,195,prior,40,3,16,2.0,196,2,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,58,Loyal customer,7.149730
87,1615297,195,prior,47,5,10,2.0,196,2,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer,7.149730
88,1765587,195,prior,52,3,12,2.0,196,3,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,58,Loyal customer,7.149730
89,745908,195,prior,57,4,11,3.0,196,3,1,...,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,58,Loyal customer,7.149730
90,2505656,222,prior,17,2,12,1.0,196,2,0,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,70,Loyal customer,6.862397
91,3268370,222,prior,38,5,15,1.0,196,6,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,70,Loyal customer,6.862397
92,2016711,290,prior,9,5,19,6.0,196,8,0,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,51,Loyal customer,7.285597
93,2706088,290,prior,28,6,10,7.0,196,16,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,51,Loyal customer,7.285597
94,1952286,331,prior,6,5,16,30.0,196,8,0,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,8,New customer,7.705128
95,3226575,360,prior,1,5,12,NaN,196,1,0,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,3,New customer,10.006250
96,1469869,377,prior,3,5,17,3.0,196,9,0,...,9.0,both,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,3,New customer,8.496552
97,1927023,387,prior,2,4,10,22.0,196,3,0,...,9.0,both,NaN,Mid-range product,Least busy,Least busy days,Most orders,8,New customer,7.396610
98,858092,420,prior,4,1,19,30.0,196,2,0,...,9.0,both,NaN,Mid-range product,Regularly busy,Busiest days,Average orders,22,Regular customer,7.387805
99,119314,420,prior,5,3,19,16.0,196,2,1,...,9.0,both,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,22,Regular customer,7.387805

In [37]:
# Creating flags 
ords_prods_merge.loc[ords_prods_merge['mean_price'] < 10, 'spending_flag'] = 'Low spender'

In [38]:
ords_prods_merge.loc[ords_prods_merge['mean_price'] >= 10, 'spending_flag'] = 'High spender'

In [39]:
# Checking frequencies of spending flags 
ords_prods_merge['spending_flag'].value_counts(dropna = False)

Low spender     31770614
High spender      634245
Name: spending_flag, dtype: int64

# Creating order_frequency flag

In [41]:
# Creating new column median_days
ords_prods_merge['median_days'] = ords_prods_merge.groupby(['user_id'])['days_since_last_order'].transform(np.median)

In [42]:
# Checking
ords_prods_merge.head(100)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,...,price_range_loc,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,mean_price,spending_flag,median_days
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.5
2,473747,1,prior,3,3,12,21.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.5
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,NaN,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.5
4,431534,1,prior,5,4,15,28.0,196,1,1,...,NaN,Mid-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.5
5,3367565,1,prior,6,2,7,19.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5
6,550135,1,prior,7,1,9,20.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.5
7,3108588,1,prior,8,1,14,14.0,196,2,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.5
8,2295261,1,prior,9,1,16,0.0,196,4,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.5
9,2550362,1,prior,10,4,8,30.0,196,1,1,...,NaN,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.5
10,2968173,15,prior,15,1,9,7.0,196,2,0,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0
11,1870022,15,prior,17,2,16,8.0,196,6,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender,10.0
12,1911383,15,prior,18,2,11,7.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender,10.0
13,2715276,15,prior,21,1,9,7.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0
14,487368,15,prior,22,1,10,14.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0
15,2293453,19,prior,2,5,14,6.0,196,3,0,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,8.372059,Low spender,6.0
16,1973799,19,prior,5,6,12,8.0,196,15,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,8.372059,Low spender,6.0
17,532817,19,prior,7,4,17,6.0,196,1,1,...,NaN,Mid-range product,Least busy,Least busy days,Average orders,9,New customer,8.372059,Low spender,6.0
18,1573906,21,prior,10,3,10,6.0,196,2,0,...,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,33,Regular customer,7.012683,Low spender,7.5
19,1593000,31,prior,10,3,8,7.0,196,17,0,...,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,20,Regular customer,8.137793,Low spender,6.0
20,2231262,31,prior,17,3,11,8.0,196,14,1,...,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,20,Regular customer,8.137793,Low spender,6.0
21,2580647,43,prior,6,4,16,4.0,196,9,0,...,NaN,Mid-range product,Least busy,Least busy days,Most orders,11,Regular customer,7.444898,Low spender,10.0
22,2187180,43,prior,9,4,12,3.0,196,1,1,...,NaN,Mid-range product,Least busy,Least busy days,Most orders,11,Regular customer,7.444898,Low spender,10.0
23,2497897,52,prior,1,1,9,NaN,196,4,0,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
24,1318871,52,prior,2,1,10,7.0,196,5,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
25,1261384,52,prior,3,1,10,7.0,196,3,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
26,580568,52,prior,5,2,10,8.0,196,6,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
27,2428073,52,prior,7,2,7,8.0,196,5,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,27,Regular customer,6.356287,Low spender,8.0
28,342306,52,prior,9,1,11,7.0,196,5,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
29,1520353,52,prior,10,2,10,8.0,196,4,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
30,2542086,52,prior,11,2,9,7.0,196,3,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
31,944694,52,prior,12,1,16,6.0,196,7,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
32,1268191,52,prior,15,2,11,8.0,196,3,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
33,1122089,52,prior,17,2,10,6.0,196,4,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
34,1498922,52,prior,18,2,10,14.0,196,6,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
35,180919,52,prior,19,3,8,8.0,196,4,1,...,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,27,Regular customer,6.356287,Low spender,8.0
36,2695875,52,prior,21,5,10,30.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
37,3205960,67,prior,1,3,11,NaN,196,1,0,...,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0
38,970922,67,prior,2,1,15,5.0,196,2,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
39,596585,67,prior,3,1,13,7.0,196,2,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
40,2037087,67,prior,4,2,9,8.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
41,2474111,67,prior,5,3,14,8.0,196,2,1,...,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0
42,1568481,67,prior,6,3,12,7.0,196,2,1,...,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0
43,2048527,67,prior,8,2,11,7.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
44,2389031,67,prior,9,2,14,7.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
45,2378562,67,prior,10,1,10,6.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
46,1515698,67,prior,11,1,11,7.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
47,1928050,67,prior,12,2,12,8.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
48,1949274,67,prior,13,1,10,6.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
49,551869,67,prior,14,1,9,7.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
50,768572,67,prior,16,4,10,9.0,196,1,1,...,NaN,Mid-range product,Least busy,Least busy days,Most orders,24,Regular customer,7.656790,Low spender,7.0
51,150528,67,prior,18,5,16,4.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
52,29758,67,prior,19,0,14,9.0,196,2,1,...,NaN,Mid-range product,Busiest day,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
53,1558976,67,prior,21,1,9,5.0,196,2,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
54,863974,67,prior,22,1,11,14.0,196,3,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
55,2308399,67,prior,23,1,14,14.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
56,2759128,81,prior,3,1,9,14.0,196,2,0,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,7,New customer,8.165385,Low spender,30.0
57,1812985,81,prior,5,2,20,30.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,7,New customer,8.165385,Low spender,30.0
58,1889835,82,prior,1,3,15,NaN,196,6,0,...,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,19,Regular customer,6.441221,Low spender,11.5
59,499460,82,prior,3,5,10,5.0,196,2,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer,6.441221,Low spender,11.5
60,2728456,82,prior,4,0,11,16.0,196,1,1,...,NaN,Mid-range product,Busiest day,Busiest days,Most orders,19,Regular customer,6.441221,Low spender,11.5
61,2653743,82,prior,6,4,9,13.0,196,5,1,...,NaN,Mid-range product,Least busy,Least busy days,Most orders,19,Regular customer,6.441221,Low spender,11.5
62,1358880,82,prior,9,1,10,30.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,19,Regular customer,6.441221,Low spender,11.5
63,343588,82,prior,10,2,11,1.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer,6.441221,Low spender,11.5
64,3034663,82,prior,15,2,11,12.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer,6.441221,Low spender,11.5
65,147262,82,prior,18,1,13,7.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,19,Regular customer,6.441221,Low spender,11.5
66,3144004,82,prior,19,2,15,8.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,19,Regular customer,6.441221,Low spender,11.5
67,2126069,98,prior,3,0,9,25.0,196,7,0,...,NaN,Mid-range product,Busiest day,Busiest days,Most orders,14,Regular customer,8.028000,Low spender,25.0
68,2210120,98,prior,7,5,14,5.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,14,Regular customer,8.028000,Low spender,25.0
69,681011,98,prior,9,3,9,30.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,14,Regular customer,8.028000,Low spender,25.0
70,2846344,98,prior,11,4,13,15.0,196,2,1,...,NaN,Mid-range product,Least busy,Least busy days,Most orders,14,Regular customer,8.028000,Low spender,25.0
71,747431,98,prior,12,6,13,30.0,196,4,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,14,Regular customer,8.028000,Low spender,25.0
72,2383054,98,prior,13,4,11,30.0,196,1,1,...,NaN,Mid-range product,Least busy,Least busy days,Most orders,14,Regular customer,8.028000,Low spender,25.0
73,1993729,98,prior,14,5,8,8.0,196,2,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,14,Regular customer,8.028000,Low spender,25.0
74,1403849,109,prior,3,3,17,9.0,196,5,0,...,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,6,New customer,5.850725,Low spender,26.0
75,520620,120,prior,1,3,11,NaN,196,2,0,...,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,3,New customer,9.385714,Low spender,19.0
76,3273029,120,prior,3,2,8,19.0,196,2,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,3,New customer,9.385714,Low spender,19.0
77,1861943,185,prior,2,1,12,25.0,196,10,0,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,6,New customer,7.715000,Low spender,25.0
78,2040988,195,prior,1,1,14,NaN,196,2,0,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
79,1680569,195,prior,8,1,9,4.0,196,2,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
80,276171,195,prior,19,5,11,3.0,196,2,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer,7.149730,Low spender,4.0
81,2744976,195,prior,22,5,10,7.0,196,2,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer,7.149730,Low spender,4.0
82,2781919,195,prior,25,1,14,4.0,196,1,1,...,NaN,Mid-range product,Regularly busy,Busiest days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
83,1738718,195,prior,31,2,8,4.0,196,2,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,58,Loyal customer,7.149730,Low spender,4.0
84,3058369,195,prior,34,3,10,6.0,196,2,1,...,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
85,1485596,195,prior,37,2,15,0.0,196,2,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer,7.149730,Low spender,4.0
86,417035,195,prior,40,3,16,2.0,196,2,1,...,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
87,1615297,195,prior,47,5,10,2.0,196,2,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,58,Loyal customer,7.149730,Low spender,4.0
88,1765587,195,prior,52,3,12,2.0,196,3,1,...,NaN,Mid-range product,Regularly busy,Least busy days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
89,745908,195,prior,57,4,11,3.0,196,3,1,...,NaN,Mid-range product,Least busy,Least busy days,Most orders,58,Loyal customer,7.149730,Low spender,4.0
90,2505656,222,prior,17,2,12,1.0,196,2,0,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,70,Loyal customer,6.862397,Low spender,5.0
91,3268370,222,prior,38,5,15,1.0,196,6,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,70,Loyal customer,6.862397,Low spender,5.0
92,2016711,290,prior,9,5,19,6.0,196,8,0,...,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,51,Loyal customer,7.285597,Low spender,7.0
93,2706088,290,prior,28,6,10,7.0,196,16,1,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,51,Loyal customer,7.285597,Low spender,7.0
94,1952286,331,prior,6,5,16,30.0,196,8,0,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,8,New customer,7.705128,Low spender,30.0
95,3226575,360,prior,1,5,12,NaN,196,1,0,...,NaN,Mid-range product,Regularly busy,Regularly busy,Most orders,3,New customer,10.006250,High spender,4.0
96,1469869,377,prior,3,5,17,3.0,196,9,0,...,NaN,Mid-range product,Regularly busy,Regularly busy,Average orders,3,New customer,8.496552,Low spender,16.5
97,1927023,387,prior,2,4,10,22.0,196,3,0,...,NaN,Mid-range product,Least busy,Least busy days,Most orders,8,New customer,7.396610,Low spender,8.0
98,858092,420,prior,4,1,19,30.0,196,2,0,...,NaN,Mid-range product,Regularly busy,Busiest days,Average orders,22,Regular customer,7.387805,Low spender,7.0
99,119314,420,prior,5,3,19,16.0,196,2,1,...,NaN,Mid-range product,Regularly busy,Least busy days,Average orders,22,Regular customer,7.387805,Low spender,7.0

In [43]:
# Creating flags 
ords_prods_merge.loc[ords_prods_merge['median_days'] > 20, 'frequency_flag'] = 'Non-frequent customer'

In [44]:
ords_prods_merge.loc[(ords_prods_merge['median_days'] > 10) & (ords_prods_merge['median_days'] <= 20), 'frequency_flag'] = 'Regular customer'

In [45]:
ords_prods_merge.loc[ords_prods_merge['median_days'] <= 10, 'frequency_flag'] = 'Frequent customer'

In [46]:
# Checking frequencies of frequency flag
ords_prods_merge['frequency_flag'].value_counts(dropna=False)

Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
NaN                             5
Name: frequency_flag, dtype: int64

In [47]:
# Exporting df to pickle file
ords_prods_merge.to_pickle(os.path.join(path, '2. Data','Prepared data', 'orders_products_aggregated.pkl'))